### ISSUE TITLE
Crash with Create on Quilt

### ISSUE THREAD

**Issue by Steveplays28** [ishland/EarlyLoadingScreen#13]
## Issue description

Works fine if `enable_mixin_pretransform` is set to `false` in the config.
Could also be an issue with the fact that I'm running on Quilt and some Fabric Loader classes are used. There's a re-entrance error in the logs which seems to cause issues further down the line.

## Version info

- Minecraft `1.20.1`
- Quilt Loader `v0.21.2`
- Quilted Fabric API `v7.4.0+0.90.0`
- Early Loading Screen `v0.1.3`
- Create Fabric `v0.5.1-d-build.1161`

## Log

https://mclo.gs/rc8aTA8

**Comment by ishland** [comment]
Resolved in 7fc51f2cb5bdb69fb3791f9785927ca2e626a49a

**Comment by Steveplays28** [comment]
Awesome, thanks ishland!
I wonder how hard it'd be to fix this issue at the source though, I might look into that at some point in the future for a PR.
