### ISSUE TITLE
Window & process naming

### ISSUE THREAD

**Issue by NerjalNosk** [ishland/EarlyLoadingScreen#14]
Not totally an issue, more of a feature request.

On some platforms, especially Linux-based ones, the window is named after its first title, and this one does not change throughout the course of its usage.

Hence, it ends up being called "Minecraft -- initializing mods" all along, even if the window title itself changed. (visible in open windows menu, and alike)

While we could be expecting, or at least hoping, for it to have a more fitting name as it is simply running, for it has finished loading.

Thus, being able to either customize the early window title, or make it be set to a default "Minecraft -- <version>" immediately, would allow for the window to be properly referenced all along.

Allowing to customize it would also allow for modpacks to have it reference their name, which would also be a positive aspect, but really only optional.

Thank you for your comprehension, and I hope to see it become true.

**Comment by ishland** [comment]
I forgot to mention that it is already implemented and it now pulls version string from fabric-loader.
