### ISSUE TITLE
[Feature] Native Wayland window creation

### ISSUE THREAD

**Issue by exalented** [ishland/EarlyLoadingScreen#15]
This project forces the game to create a wayland window to bypass XWayland issues like black bars/screen flickering.
https://github.com/wired-tomato/WayGL

It would be great to have this project to respect the `WAYLAND_DISPLAY` environment variable/WayGL. As of now the only way to use this mod on Nvidia without XWayland issues aforementioned is by:
1. setting `reuse_early_window` to **false**; thus, spawning the main game window in Wayland with WayGL.
2. Unsetting the `DISPLAY` environment variable.
   - **Note**: will otherwise cause ELS to hang the game instance before startup in these certain instances:
```
[Render thread/WARN]: Failed to create window: 
net.minecraft.class_1041$class_4716: GLFW error 65548: Wayland: The platform does not support setting the input focus
	at net.minecraft.class_1041.method_4501(class_1041.java:195) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:43) ~[lwjgl-glfw-3.3.2.jar:?]
	at org.lwjgl.system.JNI.invokePV(Native Method) ~[lwjgl-3.3.2.jar:?]
	at org.lwjgl.glfw.GLFW.glfwShowWindow(GLFW.java:2870) ~[lwjgl-glfw-3.3.2.jar:?]
	
... game hang ...
```
Here's a bit more context: https://github.com/wired-tomato/WayGL/issues/1#issuecomment-1947987368

**Comment by ishland** [comment]
Personally I think platform handling should be handled by glfw. I'm not considering adding a platform hint for window creation. 

Also, I'm unable to reproduce this issue when unsetting `DISPLAY` with and without WayGL.

**Comment by exalented** [comment]
Wayland support was recently merged into glfw. Now, simply unsetting the `DISPLAY` environment variable works great and ELS can reuse the window! Thank you for your time and consideration on this.
