### ISSUE TITLE
Continuity (& CTM most likely) connected textures not working

### ISSUE THREAD

**Issue by DadoIrie** [ishland/EarlyLoadingScreen#4]
https://mclo.gs/K3fja8v

[Continuity ](https://modrinth.com/mod/continuity) - & [CTM ](https://modrinth.com/mod/ctm-refabricated) most likely - not tested on this instance, but on my main one where I've tried both types of textures - do not work with EarlyLoadingScreen. 
Tried with various ELS configs - none worked

![image](https://github.com/ishland/EarlyLoadingScreen/assets/61109153/3792527f-9121-4638-8455-caae99b8c64f)
![image](https://github.com/ishland/EarlyLoadingScreen/assets/61109153/f1aa70bd-01c3-4c79-99cd-7b11654a07ca)

**Comment by ishland** [comment]
Fixed in commit 14ff0addab3f8cd91f80327b0df69f38a03365c9.
