### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by lostopkk** [ishland/EarlyLoadingScreen#6]
crash log: https://mclo.gs/dNFZFJ1

**Comment by ishland** [comment]
The crash is caused by the incompatibility between `particletweaks` and `particlerain` rather than EarlyLoadingScreen.

**Comment by lostopkk** [comment]
no fix to resolve this?

> The crash is caused by the incompatibility between `particletweaks` and `particlerain` rather than EarlyLoadingScreen.
